### ISSUE TITLE
More language

### ISSUE THREAD

**Issue by Roli0109** [PokeNavBot/Issue-Tracker#539] opened 2020-09-06 10:22 UTC
For example: Hungary

**Comment by dandesousa** [comment] 2020-09-07 12:49
Language for what? Bot translations? Pokemon names? Research?

**Comment by mikosoby** [comment] 2020-09-08 11:34
Not sure about the author, but my community would appreciate a slovak localization. But there are no slovak pkmn names and other things, so just regular PokeNav strings.

**Comment by dandesousa** [comment] 2020-09-12 16:59
This seems like a duplicate of #134

**Closed as completed by dandesousa** 2020-09-12 16:59 UTC
Labels: discussion, bot
