### ISSUE TITLE
Rare spawn reporting support

### ISSUE THREAD

**Issue by M3G4N5** [PokeNavBot/issue-tracker#393] opened 2019-06-02 11:59 UTC
It would be great if there was a command syntax for rare spawn reporting where people could report rare spawns by nearest PokéStop or manual address entry [optional inputs: CP, stats, IV]. Ability to then set Notify roles e.g. 100IV. Due to limited time nature of spawns, maybe also a react that people can hit if they get to the location and the Pokémon has despawned. 

Next level: have a tab in PokeNav app with map and visual cues of nearby rare spawns, research reports etc.

**Comment by dandesousa** [comment] 2019-06-02 15:30
Duplicate of #276 -- it has been linked for future reference

If implemented this would be tied to a screenshot since you can otherwise just tag a role to get the same impact.

**Closed by dandesousa** 2019-06-02 15:30 UTC
