### ISSUE TITLE
Toggle auto-member-list on raids

### ISSUE THREAD

**Issue by MagicSword89** [PokeNavBot/issue-tracker#232] opened 2018-11-20 02:21 UTC
Possibility to toggle the server option of auto-member-list. Similar to the auto-cheatsheet or the auto-counterlist, introduce a self updating auto-member-list in raid channels and maybe even in the embed messages from the raid-report-lobby.
~posting for a friend

**Comment by dandesousa** [comment] 2018-11-21 00:35
this is a duplicate of #136

**Closed by dandesousa** 2018-11-21 00:35 UTC
