### ISSUE TITLE
Control pokenav commands that can be used in raid channels.

### ISSUE THREAD

**Issue by ukbigdave** [PokeNavBot/Issue-Tracker#645] opened 2021-07-20 00:15 UTC
**Is your feature request related to a problem? Please describe.**
Unfortunately during go-fest some servers were spammed with people using verify, help, sub, subs in raid channels. These idiots ruin the experience for everyone else. Whilst we auto delete the commands, the embeds are left. This effects users in channels and impacts bot performance. The amount was impossible to moderate on big servers. 

**Describe the solution you'd like**
It was already suggested that this was a big change as commands need to be updated one by one. 

$r can only be used in channels specified as raid channels. Maybe classify each command into groups, then assign what channels can use which groups (profile commands, subs, badges maybe). 

**Describe alternatives you've considered**
Other bots to clean up the PokeNav responses to non $r commands. 

**Additional context**

**Comment by dandesousa** [comment] 2021-07-23 13:43
Duplicate of #139

**Closed as completed by dandesousa** 2021-07-23 13:43 UTC
