### ISSUE TITLE
Automatically Ask Users to Select Stops/Gyms when Bot Matches Multiple

### ISSUE THREAD

**Issue by Kdog0073** [PokeNavBot/issue-tracker#462] opened 2019-11-10 02:08 UTC
Currently for quests, raids, and EXs, when a user posts either a picture or enters a command, the location is not displayed on the embed when the bot matches multiple locations.

If a user notices, they can retype the name via command or tools and a menu comes up which asks which gym/stop it is. This is also the automatic behavior when entering a gym with a duplicate name inside a train channel.

The ask is to extend this behavior to the raid, ex, and quest commands and ocr. This would be especially useful for sponsored stops/gyms.

**Comment by dandesousa** [comment] 2019-11-10 10:44
Duplicate of #130

**Closed** 2019-11-10 10:43 UTC
Labels: duplicate
