### ISSUE TITLE
Team Rocket Leader Reporting

### ISSUE THREAD

**Issue by geezfools** [PokeNavBot/issue-tracker#457] opened 2019-11-08 17:28 UTC
Would love to see a feature similar to Field Research, but for Team Leader Hideouts related to rocket stops. While rocket stops are random and come and go, the team leader hideouts are at the same pokestop for the entire day, the leader is the same for all trainers and as far as we know, the pokemon encountered are the same for all trainers as well.

If shadow pokemon battled are confirmed to be the same, I would see the bot asking for which team leader and then which three pokemon you need to battle.

**Comment by Kdog0073** [comment] 2019-11-16 01:47
I have observed the pokemon to be the same for everyone at the same stop, same day

**Comment by mikosoby** [comment] 2020-01-07 15:21
Not sure if this happens changes per location but we the Team GO Rocket Leaders disapear at 10 PM every day.
Also I can confirm, that the Leaders and their Pokémon are the same for everybody.

**Comment by oneone84** [comment] 2020-01-09 15:09
Our community would love this, my guess is that the code for field research channels could be reused:
1. stop name is used in the same way
2. instead of reporting a reward, we report leader name (Arlo,Cliff,Sierra,Giovanni)
3. there is no task, but optionally you could implement the ability to report the pokemon used by the leader, moveset could also be interesting but might be cumbersome both to code and report.

Support 2 new channels, default names:
#announce-rocket-leader
#active-rocket-leaders
(or similar, mabye "present" is better than "active" when talking about leaders)

Both comments above seem correct :)

**Comment by mikosoby** [comment] 2020-03-10 10:08
bump

**Comment by Hedva** [comment] 2020-03-16 07:52
Would also like to see this

**Comment by DMS27** [comment] 2020-07-09 11:04
Agree that this would be a great addition.

**Comment by dandesousa** [comment] 2020-11-06 23:42
Honestly I think this is like wild spawn reporting -- rocket stops only last 30 minutes -- by the time you report them they are maybe gone with no idea what the time is. Going to close this because there's no realistic chance this will be added without some more guarantees on rocket stop reporting.

**Comment by qwertyperky** [comment] 2020-11-07 00:05
This request was for the leaders if you misread it, not the 30 minute grunts @dandesousa

**Comment by mikosoby** [comment] 2020-12-09 15:32
As @qwertyperky is saying this is for the GO Rocket Leader, that are available from ~6 am until 10pm everday. So something like Field Research..
Would be very beneficial to implement.

**Comment by geezfools** [comment] 2021-01-20 00:55
So confused how this ended up getting closed... My description over a year ago is still accurate. @dandesousa your lack of understanding of how hideouts and rocket stops work isn't reason to close this, especially considering the number of people who would like to see it implemented. Please reconsider...

**Comment by dandesousa** [comment] 2021-02-09 12:55
I did mis-read this at the time that it was grunts and not leaders.

**Comment by dandesousa** [comment] 2021-02-09 12:56
That being said, it's not likely this will end up getting implemented any faster -- too many feature requests, too little time and honestly, there is not that much utility to this as people suspect. 

This is very similar to research and research is a relatively under utilized feature in the bot. Team Rocket Leaders are both less common and have in game support for proximately locating them.

**Closed** 2021-08-17 07:43 UTC
Labels: enhancement, wontfix, bot
