### ISSUE TITLE
insert-cheatsheet

### ISSUE THREAD

**Issue by Roli0109** [PokeNavBot/Issue-Tracker#558] opened 2020-11-06 22:14 UTC
the insert-cheat sheet I can change, for example translate the commands that are there

**Comment by dandesousa** [comment] 2020-11-06 23:31
Honestly this would probably just be a part of the localization effort when that happens #134

**Comment by dandesousa** [comment] 2020-11-06 23:31
Duplicate of #134

**Closed as completed by dandesousa** 2020-11-06 23:31 UTC
